# Server
server.port=${PORT:8080}

# Database Configuration (Railway provides env variables)
spring.datasource.url=jdbc:mysql://root:lIuROVKDosXVsoFTOUXrIgZhJLsgDbqq@shuttle.proxy.rlwy.net:59765/railway
spring.datasource.username=root
spring.datasource.password=lIuROVKDosXVsoFTOUXrIgZhJLsgDbqq
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Configuration
skillvault.app.jwtSecret=${JWT_SECRET}
skillvault.app.jwtExpirationMs=86400000
skillvault.app.jwtSecret=${JWT_SECRET:skillvaultsupersecurekey2026verylong12345cihoschoishcohwoihfowf89w9cgsbcnoiwnocwcw}

# Error Handling
server.error.include-message=always
